### ISSUE TITLE
AMD-3900x+X570+GTX760

### ISSUE THREAD

**Issue by Curiouserw** [YahuiWong/AMD-5950x_MSI-MEG-UNIFY-X570_GTX760_hackintosh_opencore#1]
兄弟，你是怎么制作EFI相关文件的？可否加个微信或QQ

**Comment by YahuiWong** [comment]
使用这个efi遇到什么问题了吗

**Comment by Curiouserw** [comment]
> 使用这个efi遇到什么问题了吗

是我的CPU型号跟你的不太一样。我要制作符合自己硬件条件的EFI，怎么做？
我的硬件详细配置：
  CPU：AMD 3900x 
  主板：华硕 X570-PLUS
  显卡1：GTX 760
  显卡2：GTX 2060s
  其他：忽略

**Comment by YahuiWong** [comment]
我的主板是徽星的，不能保证你可以使用这个EFI
